services:
  crm-api:
    image: crm-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: 'Ibdibn2814!'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
